[package]
name = "crawlnicle"
version = "0.1.0"
edition = "2021"
default-run = "crawlnicle"

[lib]
name = "lib"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
argh = "0.1"
axum = "0.6"
bytes = "1.4"
chrono = { version = "0.4", features = ["serde"] }
dotenvy = "0.15"
feed-rs = "1.3"
maud = { version = "0.25", features = ["axum"] }
notify = "6"
once_cell = "1.17"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_with = "3"
sqlx = { version = "0.6", features = [
  "runtime-tokio-native-tls",
  "postgres",
  "macros",
  "migrate",
  "chrono",
] }
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tower = "0.4"
tower-livereload = "0.7"
tower-http = { version = "0.4", features = ["trace"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
validator = { version = "0.16", features = ["derive"] }
